# Generated by Django 5.0.6 on 2024-09-13 14:21

import precise_bbcode.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_bb__content2_rendered_bb_content2'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBCodeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('_content_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('content', precise_bbcode.fields.BBCodeTextField(no_rendered_field=True)),
            ],
        ),
    ]
